package com.fiszki.fiszkiproject.exceptions.common;

public enum APIErrors {
	USER_NOT_IN_DATABASE,
	INVALID_PASSWORD,
	DISPLAY_NAME_TOO_SHORT,
	DISPLAY_NAME_ALREADY_TAKEN,
	PASSWORD_TOO_SHORT,
	PASSWORD_HAS_NO_CAPITAL_LETTERS,
	PASSWORD_HAS_NO_SPECIAL_CHARS,
	PASSWORDS_DO_NOT_MATCH
}
